import stylelintConfigStandard from 'stylelint-config-standard';
import stylelintScss from 'stylelint-config-standard-scss';
import stylelintOrder from 'stylelint-order';

export default {
    extends: [stylelintConfigStandard, stylelintScss],
    plugins: [stylelintOrder],
    rules: {
        'scss/no-global-function-names': null,
        'scss/dollar-variable-no-missing-interpolation': null,
        'scss/at-rule-no-unknown': null,
        'selector-pseudo-class-no-unknown': [
            true,
            { ignorePseudoClasses: ['global'] },
        ],
        'selector-pseudo-element-no-unknown': [
            true,
            { ignorePseudoElements: ['deep'] },
        ],
        'block-no-empty': true,
        'selector-max-id': 0,
        'no-descending-specificity': true,
        'rule-empty-line-before': [
            'always',
            { except: ['first-nested'], ignore: ['after-comment'] },
        ],
        'selector-class-pattern': null,
        'order/order': ['custom-properties', 'declarations'],
        'order/properties-order': [
            [
                'all',
                'position',
                'top',
                'right',
                'bottom',
                'left',
                'display',
                'flex-flow',
                'flex-wrap',
                'flex-grow',
                'flex-shrink',
                'flex-basis',
                'flex-direction',
                'grid-template-columns',
                'grid-template-rows',
                'grid-template-areas',
                'grid-auto-flow',
                'grid-auto-columns',
                'grid-auto-rows',
                'grid-gap',
                'grid-area',
                'grid-column',
                'grid-row',
                'place-items',
                'place-content',
                'justify-content',
                'align-content',
                'align-items',
                'justify-self',
                'align-self',

                'width',
                'height',
                'min-width',
                'min-height',
                'max-width',
                'max-height',
                'margin',
                'padding',
                'gap',

                'background',
                'background-color',
                'border',
                'border-radius',
                'box-shadow',
                'opacity',

                'font',
                'font-size',
                'font-weight',
                'line-height',
                'text-align',
                'color',

                'transition',
                'animation',
                'z-index',
            ],
            { unspecified: 'bottomAlphabetical' },
        ],
    },
    fix: true,
};
